export const FEATURE_CODES = {
  FACILITY: 'FACILITY',
  PARKING_STATUS: 'PARKING_STATUS',
  VOTE: 'VOTE',
}

export const DEFAULT_COMPLEX_FEATURES = {
  [FEATURE_CODES.FACILITY]: true,
  [FEATURE_CODES.PARKING_STATUS]: true,
  [FEATURE_CODES.VOTE]: true,
}

export const FEATURE_LABELS = {
  [FEATURE_CODES.FACILITY]: '시설/예약',
  [FEATURE_CODES.PARKING_STATUS]: '주차 현황',
  [FEATURE_CODES.VOTE]: '전자투표',
}
